dishes= input("enter 3 of your favorite dish:")
dish_1 = ("rice")
dish_2 = ("beans")
dish_3 = ("dodo")
dishes = (dish_1 ,dish_2, dish_3)
print(dishes)
print(f"{dish_1}\n{dish_2}\n{dish_3}")

#2 Tuple and input
print("ask the user for 5 best friends name")
bf_1 = input("enter your bf_1")
bf_2 = input("enter your bf_2")
bf_3 = input("enter your bf_3")
bf_4 = input("enter your bf_4")
bf_5 = input("enter your bf_5")
friends = (bf_1, bf_2, bf_3, bf_4, bf_5)
print(friends)
print(friends[::-1])

# #3
print("enter 5 nigerian states")
state_1= input("Enter your state: ")
state_2= input("Enter your state: ")
state_3= input("Enter your state: ")
state_4= input("Enter your state: ")
state_5= input("Enter your state: ")
Nigerian_state = (state_1,state_2, state_3, state_4, state_5)
print(Nigerian_state)
print(Nigerian_state[0])
print(Nigerian_state[4])
print("Lagos"  in Nigerian_state)
# print(f"{len(Nigerian_state)}")

#4
print("user enter your details")
first_name = input("Enter your first name")
age = input("Enter your age")
Favorite_color = input("Enter your fav color")
Home_town = input("Enter your hometown")
profile= (first_name, age, Favorite_color, Home_town)
print(profile)
print(first_name)
print(age)
print(Favorite_color)
print(Home_town)
print(f"Ngozi profile\n=========================\nFirst name:{first_name}\nAge:{age}\nFavorite color:{Favorite_color}\nHomeTown: {Home_town}\n======================")

#5Modify tuple indirectly
print("Ask user tro enter their list")
item_1 = input("Enter your first item: ")
item_2 = input("Enter your second itemm")
item_3 = input("Enter your third item")
shopping_list = (item_1,item_2,item_3)
print(shopping_list)
lst = list(shopping_list)
print("Ask user to enter tnew list")
item_4 = input("Enter the new item 1")
item_5 = input("Enter your new item 2")
new_list =(f"{item_4}, {item_5}")
lst.append(new_list)
print(lst)
shopping_list= tuple(lst)
print(shopping_list)

#6 
days_of_the_week = ("sunday", "monday", "tuesday","wednesday", "thursday", "friday","saturday")
Months_of_the_year = ("January", "Febuary", "March", "April","May","June","July", "August","September","October","November","December" )
print(days_of_the_week)
print(Months_of_the_year)
print("Enter your details")
Student_name = input("Enter your name:")
Gender = input("Enter your: ")
course_track = input("Enter your track:")
current_month_num = input("enter your month num:")
current_day_num = input("Enter your current day num:")
print(f"Student Attendance tracker\n==============================\nStudent name:\t{Student_name}\nGender:\t{Gender}\nCourse track:\t{course_track}\nCurrent Month:\t{current_month_num}\nCurrent Day:\t{current_day_num}\n=================================")
